#!/usr/bin/env node
'use strict';
// AUTO-GENERATED by scripts/generate-bins.js — DO NOT EDIT.
// Edit providers/providers.json and re-run `node scripts/generate-bins.js`.

// Custom provider: delegate to the provider's own self-contained bin.
require('../providers/agy/bin/grok-agy.js');
